### ISSUE TITLE
Upgrading to golang 1.7 but "/etc/alternatives/golang-home-link" still point to  "/usr/local/golang/1.6/go"

### ISSUE THREAD

**Issue by tjyang** [jackscott/golang-formula#3]
Hi 

I modified  defaults.yaml with 1.7 new release

```
{% load_yaml as lookup_map %}
default:
  prefix: /usr/local
  go_root: /usr/local/go
  go_path: /var/lib/golang
  version: "1.7"
  archive_hash: "702ad90f705365227e902b42d91dd1a40e48ca7f67a2f4b2fd052aaa4295cd95"
Debian: {}
RedHat: {}
{% endload %}

```

but I am still getting following old link to 1.6

```
[root@server01 ~]# ls -ld /etc/alternatives/golang-home-link
lrwxrwxrwx 1 root root 25 Aug 16 17:01 /etc/alternatives/golang-home-link -> /usr/local/golang/1.6/go/
[root@server01 ~]# 
```

Could not find "1.6" variable  got set anywhere else beside defaults.yaml  in the formula files.
